theme: jekyll-theme-minimal
title: 'Bioinformatics: Command Line/R Prerequisites 2020'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule

  - heading: Resources
  - title: Zoom help
    url: base/zoom
  - title: Slack help
    url: base/slack
  - title: Software and Links
    url: software_scripts/software
  - title: Cheat Sheets
    url: base/cheatSheetIndex

  - heading: Intro CLI
  - title: Logging in
    url: CLI_Intro/logging-in
  - title: Introduction to the Command Line part 1
    url: CLI_Intro/intro-cli-part1
  - title: Introduction to the Command Line part 2
    url: CLI_Intro/intro-cli-part2
  - title: The cluster and modules
    url: CLI_Intro/cluster

  - heading: Introduction to Python
  - title: Python Part1, Background
    url: Intro_to_Python/Intro_To_Python
  - title: Python Part2, Data Types
    url: Intro_to_Python/Part2_BasicDataTypes
  - title: Python Part2, Solutions
    url: Intro_to_Python/Part2_solutions
  - title: Python Part3, Flow Control
    url: Intro_to_Python/Part3_FlowControl
  - title: Python Part3, Solutions
    url: Intro_to_Python/Part3_solutions
  - title: Python Part4, Working with Files
    url: Intro_to_Python/Part4_FilesEtc

  - heading: Advanced CLI
  - title: Advanced Command Line
    url: Advanced_CLI/advanced-command-line
  - title: Advanced Challenge Solutions
    url: Advanced_CLI/advanced-challenge-solutions
  # - title: Using screen to manage multiple projects
  #   url: Advanced_CLI/screen
  - title: A Simple Bioinformatics Workflow
    url: Advanced_CLI/bioworkflow

  - heading: Software Installation
  - title: Using make and cmake
    url: software_install/make
  - title: Using Conda
    url: software_install/conda

  - heading: Getting set up with AWS
  - title: AWS Event Engine
    url: Intro_to_R/AWS/
  - title: Starting and Stopping your AWS Instance
    url: Intro_to_R/AWS/start_stop/

  - heading: Introduction to R
  - title: Introduction to R
    url: Intro_to_R/Intro2R/Intro2R_main
  - title: Introduction to tidyverse
    url: Intro_to_R/Intro2R/Intro_to_tidyverse_and_ggplot2_prepare_fixed
  # - title: Introduction to tidyverse, part II
  #   url: intro_R/tidyverse2
  # - title: Linear modeling in R
  #   url: intro_R/linear_models
