theme: jekyll-theme-minimal
title: 'Bioinformatics: Command Line/R Prerequisites 2020'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Intro to the Workshop and Core
    url: welcome
  - title: Schedule
    url: base/schedule
  - title: Software and Links
    url: software_scripts/software

  - heading: Intro CLI
  - title: Introduction to the Command Line part 1
    url: CLI_Intro/intro-cli-part1
  # - heading: Advanced CLI
  # - title: Advanced Command Line
  #   url: adv_cli/advanced_cli
  # - title: Advanced Challenge Solutions
  #   url: adv_cli/advanced_cli_solutions
  # - title: Environment Variables
  #   url: adv_cli/environment
  # - title: Using screen to manage multiple projects
  #   url: adv_cli/screen
  - heading: Introduction to Python
  - title: Python Part1, Background
    url: Intro_to_Python/Intro_To_Python.md
  - title: Python Part2, Data Types
    url: Intro_to_Python/Part2_BasicDataTypes.md
  - title: Python Part3, Flow Control
    url: Intro_to_Python/Part3_FlowControl.md
  - title: Python Part4, Working with Files
    url: Intro_to_Python/Part4_FilesEtc.md
  - heading: Introduction to R
  - title: Introduction to R
    url: Intro_to_R/Intro2R/Intro2R_main
  # - title: Introduction to tidyverse, part I
  #   url: intro_R/tidyverse1
  # - title: Introduction to tidyverse, part II
  #   url: intro_R/tidyverse2
  # - title: Linear modeling in R
  #   url: intro_R/linear_models
  # - heading: Spreadsheets
  # - title: Working with spreadsheets
  #   url: adv_cli/advanced_cli
  # - heading: Bioinformatics
  # - title: A Simple Bioinformatics Workflow
  #   url: adv_cli/advanced_cli_solutions
  # - heading: ETC
  # - title: Closing Thoughts
  #   url: adv_cli/environment
  # - heading: Support
  # - title: Using Slack in this workshop
  #   url: base/slack
  # - title: Using Zoom in this workshop
  #   url: base/zoom
  # - title: Cheat Sheets
  #   url: base/cheatSheetIndex
